site_name: Jeep Tech Pages
site_description: Jeep guide to maintenance, modifications, and performance covering engines, transmissions, transfer cases, drive shafts, axles, wheels, and tires.
site_url: https://terryhowe.github.io/JeepTech/
site_author: Terry L. Howe

edit_uri: edit/main/docs/

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - django

nav:
  - Home:
  - Applications:
      - applications/
      - Speedometer: applications/speedometer.md
      - Tire Calculator: applications/tire.md
      - Gear Analyzer: applications/gear.md
  - Axles:
      - axle/
      - General: axle/general/
      - Factory: axle/factory/
      - Upgrades: axle/upgrades/
  - Engine:
      - engine/
      - General: engine/general/
      - Factory: engine/factory/
      - Upgrades: engine/upgrades/
  - Transmission:
      - transmission/
      - General: transmission/general/
      - Factory: transmission/factory/
      - Upgrades: transmission/upgrades/
  - Transfer Cases:
      - xfer/
      - General: xfer/general/
      - Factory: xfer/factory/
      - Upgrades: xfer/upgrades/
  - Electrical:
      - electrical/
      - Gauges: electrical/gauges/
  - Suspension:
      - suspension/
      - Custom CJ: suspension/custcj/
  - Steering:
      - steer/
  - Body:
      - body/
  - Drive Shaft:
      - shaft/
  - Wheels & Tires:
      - wheel/
      - tire/
  - Winches:
      - winch/
  - Models:
      - models/
  - Military:
      - military/
  - History:
      - history/
  - Personal:
      - Terry's Jeeps:
          - terry/
          - CJ7: terry/cj7/
          - CJ6: terry/cj6/
          - Bike: terry/bike/
          - Trail Reports:
              - terry/trail/21r9807.md
              - terry/trail/liorct.md
              - terry/trail/md9801.md
              - terry/trail/wl9907.md
              - terry/trail/ba9809.md
              - terry/trail/florida.md
              - terry/trail/lc98_main.md
              - terry/trail/hc.md
              - terry/trail/tg9803.md
              - terry/trail/mo980919.md
      - Everett: everetthowe/
      - Bell: bell/
      - Thing: thing/
  - Bibliography: bibliography.md

docs_dir: docs
site_dir: site

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - meta

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TerryHowe/JeepTech