site_name: Jeep Tech Pages
site_description: Jeep guide to maintenance, modifications, and performance covering engines, transmissions, transfer cases, drive shafts, axles, wheels, and tires.
site_url: https://terryhowe.github.io/JeepTech/
repo_url: https://github.com/TerryHowe/JeepTech
site_author: Terry L. Howe

edit_uri: blob/main/docs/

theme:
  name: material
  features:
    - content.action.edit

docs_dir: docs
site_dir: site

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - meta

plugins:
   - search
   - awesome-nav

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TerryHowe/JeepTech