nav:
  - "*"
  - d318.md
  - d360.md
  - amc150.md
  - amc232.md
  - gm173.md
  - amc242.md
  - perkins192.md
  - amc258.md
  - amc304.md
  - amc327.md
  - amc360.md
  - amc401.md
  - gm151.md
  - dauntless350.md
  - dauntless225.md
  - tornado230.md
  - hurricane134.md
  - hurricane226.md
  - godevil134.md
